# Generated by Django 3.0.5 on 2020-12-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201208_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_feedback',
            name='checkbox',
            field=models.BooleanField(default=True),
        ),
    ]
