# Generated by Django 3.0.5 on 2020-12-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201210_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapping',
            old_name='branch_id',
            new_name='branchid',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='category_id',
            new_name='categoryid',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='college_id',
            new_name='collegeid',
        ),
    ]
