# Generated by Django 3.0.5 on 2020-12-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201211_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='collegeid',
            field=models.IntegerField(),
        ),
    ]
